import { PRODUCT_EVENTS } from "./products/product-events";

export const EVENTS = {
    // USER
    USER_CREATED: "USER_CREATED",
    USER_LOGGED_IN: "USER_LOGGED_IN",

    // PRODUCT
    ...PRODUCT_EVENTS,

    // ORDER
    ORDER_CREATED: "ORDER_CREATED",
    ORDER_UPDATED: "ORDER_UPDATED",
    ORDER_CANCELLED: "ORDER_CANCELLED",
    ORDER_PAYMENT_COMPLETED: "ORDER_PAYMENT_COMPLETED",
    ORDER_PAYMENT_FAILED: "ORDER_PAYMENT_FAILED",
    ORDER_SHIPMENT_CREATED: "ORDER_SHIPMENT_CREATED",
    ORDER_SHIPMENT_UPDATED: "ORDER_SHIPMENT_UPDATED",
    ORDER_COMPLETED: "ORDER_COMPLETED",
} as const;
