export const DOMAIN_ERRORS = {
    EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    INVALID_PRODUCT: "INVALID_PRODUCT",
} as const;

export type EMAIL_ALREADY_REGISTERED_ERROR =
    typeof DOMAIN_ERRORS.EMAIL_ALREADY_REGISTERED;
export type INVALID_CREDENTIALS_ERROR =
    typeof DOMAIN_ERRORS.INVALID_CREDENTIALS;
export type PERMISSION_DENIED_ERROR = typeof DOMAIN_ERRORS.PERMISSION_DENIED;
export type INVALID_PRODUCT_ERROR = typeof DOMAIN_ERRORS.INVALID_PRODUCT;

export type DOMAIN_ERRORS = (typeof DOMAIN_ERRORS)[keyof typeof DOMAIN_ERRORS];
